---
# Handler to handle DB tier notifications

- name: restart postgresql
  become: yes
  become_user: root
  service:
    name: postgresql
    state: restarted
#
#- name: restart iptables
#  service: name=iptables state=restarted
