---
# This role will download and install jupyterhub server.

# update apt cache
- name: Update apt cache
  become: yes
  become_user: root
  apt:
    update_cache: yes

# install jupyterhub depenencies
- name: install jupyterhub dependencies
  become: yes
  become_user: root
  apt:
    name:
      - npm
      - nodejs
      - libzmq3-dev
    state: present

# install ubuntu 16.04 jupyterhub depenencies
- name: install ubuntu 16.04 jupyterhub dependencies
  become: yes
  become_user: root
  apt:
    name:
      - nodejs-legacy
    state: present
  when: server_ubuntu_version == "16.04"

# install proxy using npm
#     sudo npm install -g configurable-http-proxy
- name: install configurable-http-proxy (npm)
  become: yes
  become_user: root
  npm:
    name: configurable-http-proxy
    global: yes
    state: latest

# cython in python 3.
- name: install cython
  become: yes
  become_user: root
  pip:
    executable: pip3
    name: cython
    state: latest

# pyOpenSSL in python 3.
- name: install pyOpenSSL
  become: yes
  become_user: root
  pip:
    executable: pip3
    name: pyOpenSSL
    state: latest

# install jupyterhub and ipython notebook in python 3.
- name: install jupyterhub and ipython notebook
  become: yes
  become_user: root
  pip:
    executable: pip3
    name:
      - jupyterhub
      - ipython[notebook]
      - jupyterhub-systemdspawner
      - jupyter_contrib_nbextensions
      - jupyter_nbextensions_configurator
      - jupyterlab
    state: latest

# ==> configuration

# create jupyterhub config folder (defauts to /etc/jupyterhub)
- name: create jupyterhub config folder
  become: yes
  become_user: root
  file:
    path: "{{jupyterhub_config_folder}}"
    state: directory

# check if configuration file already there.
- name: check if jupyterhub_config.py exists
  stat:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
  register: jupyterhub_config

# initialize jupyterhub configuration if not already there.
- name: initialize jupyterhub configuration
  become: yes
  become_user: root
  shell: jupyterhub --generate-config
  args:
    chdir: "{{jupyterhub_config_folder}}"
  when: jupyterhub_config.stat.exists == False

# check if environment file already there.
- name: check if jupyterhub_environment exists
  stat:
    path: '{{jupyterhub_config_folder}}/jupyterhub_environment'
  register: jupyterhub_environment

# Create jupyterhub_environment if not already there.
- name:  Create jupyterhub_environment if not already there
  become: yes
  become_user: root
  template:
    src: jupyterhub_environment.j2
    dest: /etc/jupyterhub/jupyterhub_environment
  when: jupyterhub_environment.stat.exists == False

# add a token (no default - have to set this yourself)
- name: Add proxy token value.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.JupyterHub.proxy_auth_token = '{{jupyterhub_configproxy_auth_token}}'"
  when: jupyterhub_configproxy_auth_token != ""

# add admin_users
- name: Add proxy token value.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.Authenticator.admin_users = [ {{jupyterhub_admin_user_list}} ]"
  when: jupyterhub_admin_user_list != ""

# add white list if one specified.
- name: Add proxy token value.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.Authenticator.whitelist = [ {{jupyterhub_whitelist_list}} ]"
  when: jupyterhub_whitelist_list != ""

# add certificate to jupyterhub config.
- name: add certificate to jupyterhub config.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.JupyterHub.ssl_cert = '{{ jupyterhub_ssl_certificate_path }}'"
  when: jupyterhub_ssl_certificate_path != ""
  
# add private key to jupyterhub configuration.
- name: Add private key to jupyterhub configuration.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.JupyterHub.ssl_key = '{{ jupyterhub_ssl_private_key_path }}'"
  when: jupyterhub_ssl_private_key_path != ""

# copy default SSL cert and key to jupyterhub config folder.
#- name: initialize jupyterhub configuration
#  become: yes
#  become_user: root
#  shell: openssl req -x509 -newkey rsa:4096 -keyout jupyterhub_key.pem -out jupyterhub_cert.pem -days 3650 -nodes
#  args:
#    chdir: "{{jupyterhub_config_folder}}"

#- name: copy private key
#  become: yes
#  become_user: root
#  copy:
#    src: /etc/ssl/private/ssl-cert-snakeoil.key
#    dest: "{{jupyterhub_config_folder}}/jupyterhub_key.pem"

#- name: copy public certificate
#  become: yes
#  become_user: root
#  copy:
#    src: /etc/ssl/certs/ssl-cert-snakeoil.pem
#    dest: "{{jupyterhub_config_folder}}/jupyterhub_cert.pem"

# generate OpenSSL private key.
- name: Generate an OpenSSL private key.
  become: yes
  become_user: root
  openssl_privatekey:
    path: "{{ jupyterhub_config_folder }}/jupyterhub_key.pem"
  when: jupyterhub_ssl_certificate_path == "" and jupyterhub_ssl_private_key_path == ""

# create certificate signing request (CSR)
- name: Generate an OpenSSL CSR.
  become: yes
  become_user: root
  openssl_csr:
    path: "{{ jupyterhub_config_folder }}/jupyterhub.csr"
    privatekey_path: "{{ jupyterhub_config_folder }}/jupyterhub_key.pem"
    common_name: "{{ server_name }}"
  when: jupyterhub_ssl_certificate_path == "" and jupyterhub_ssl_private_key_path == ""

# generate certificate
- name: Generate a Self-Signed OpenSSL certificate.
  become: yes
  become_user: root
  openssl_certificate:
    path: "{{ jupyterhub_config_folder }}/jupyterhub_cert.pem"
    privatekey_path: "{{ jupyterhub_config_folder }}/jupyterhub_key.pem"
    csr_path: "{{ jupyterhub_config_folder }}/jupyterhub.csr"
    provider: selfsigned
  when: jupyterhub_ssl_certificate_path == "" and jupyterhub_ssl_private_key_path == ""

# add certificate to jupyterhub config.
- name: add certificate to jupyterhub config.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.JupyterHub.ssl_cert = '{{jupyterhub_config_folder}}/jupyterhub_cert.pem'"
  when: jupyterhub_ssl_certificate_path == "" and jupyterhub_ssl_private_key_path == ""

# add private key to jupyterhub configuration.
- name: Add private key to jupyterhub configuration.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.JupyterHub.ssl_key = '{{jupyterhub_config_folder}}/jupyterhub_key.pem'"
  when: jupyterhub_ssl_certificate_path == "" and jupyterhub_ssl_private_key_path == ""

# configure jupyterhub to use systemd spawner.
- name: configure jupyterhub to use systemd spawner.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "c.JupyterHub.spawner_class = 'systemdspawner.SystemdSpawner'"

# FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy': 'configurable-http-proxy'
# If you run jupyterhub on startup with systemd, and it won't start, and you encounter the following error when you run "sudo service jupyterhub status":
#   File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
#     raise child_exception_type( errno_num, err_msg, err_filename )
# "FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy': 'configurable-http-proxy'"
# It is likely that the proxy executable is not on systemd's PATH.
# Try making a link to the file  /usr/local/bin/configurable-http-proxy in /usr/bin: 
#     sudo ln -s /usr/local/bin/configurable-http-proxy /usr/bin/configurable-http-proxy
# If this fixes it, you should remove that symbolic link and specify the path in your jupyter_config.py:
# "You can also set an absolute path in jupyterhub_config.py: `c.ConfigurableHTTPProxy.command = '/usr/local/bin/configurable-http-proxy'`, but there's a very good chance that there could be other PATH-related issues as well."
# - from https://github.com/jupyterhub/jupyterhub/issues/930

# configure jupyterhub with full path to configurable-http-proxy.
- name: configure jupyterhub with full path to configurable-http-proxy.
  become: yes
  become_user: root
  lineinfile:
    path: '{{jupyterhub_config_folder}}/jupyterhub_config.py'
    line: "#c.ConfigurableHTTPProxy.command = '{{jupyterhub_proxy_command_path}}'"
  when: jupyterhub_proxy_command_path != ""

# ==> systemd service

# Create systemd service for jupyterhub.
- name: Create systemd service for jupyterhub
  become: yes
  become_user: root
  template:
    src: jupyterhub.service.j2
    dest: /etc/systemd/system/jupyterhub.service

# Enable jupyterhub service
- name: Enable jupyterhub service
  become: yes
  become_user: root
  service:
    name: jupyterhub
    enabled: True
    use: service

# Start jupyterhub and set as a startup service
- name: Enable jupyterhub as a startup service
  become: yes
  become_user: root
  service:
    name: jupyterhub
    state: started
    enabled: yes

# open firewall for jupyterhub
- name: Allow jupyterhub port
  become: yes
  become_user: root
  ufw:
    rule: allow
    port: 8000

# add turning on nbextensions

# install juptyer nbextensions
# (sudo -H) jupyter contrib nbextension install --system --symlink
- name: install juptyer nbextensions
  become: yes
  become_user: root
  shell: jupyter contrib nbextension install --system --symlink

# enable nbextensions_configurator.
# (sudo -H) jupyter nbextensions_configurator enable --system
- name: enable nbextensions_configurator
  become: yes
  become_user: root
  shell: jupyter nbextensions_configurator enable --system

# and install table of contents in jupyterlab.
# (sudo -H) jupyter labextension install jupyterlab-toc
#- name: install jupyterlab extension jupyterlab-toc
#  become: yes
#  become_user: root
#  shell: jupyter labextension install jupyterlab-toc

# if R installed, should also install R jupyter kernel.

# sudo -E apt-get install build-essential gfortran libcurl4-gnutls-dev;
# install R jupyter kernel dependencies
#- name: install R jupyter kernel dependencies
#  become: yes
#  become_user: root
#  apt:
#    name:
#     - build-essential 
#     - nodejs
#     - libzmq3-dev
#    state: present

# install R packages.
# sudo -E R -e "install.packages( c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'), c( '/usr/local/lib/R/site-library'), repos='http://cran.us.r-project.org')"
#- name: install R packages required for R jupyter kernel
#  become: yes
#  become_user: root
#  shell: R -e "install.packages( c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'), c( '/usr/local/lib/R/site-library'), repos='http://cran.us.r-project.org')"

# install IRKernel R package
# sudo -E R -e "devtools::install_github('IRkernel/IRkernel')"
#- name: install IRKernel R package for R jupyter kernel
#  become: yes
#  become_user: root
#  shell: R -e "devtools::install_github('IRkernel/IRkernel')"

# install R jupyter kernel
# sudo -E R -e "IRkernel::installspec(user = FALSE)"
#- name: install R jupyter kernel
#  become: yes
#  become_user: root
#  shell: R -e "IRkernel::installspec(user = FALSE)"
