---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: reset ufw
  become: yes
  become_user: root
  ufw:
    state: reset
    
- name: enable ufw
  become: yes
  become_user: root
  ufw:
    state: enabled
