---
# This playbook will install and configure mariadb.

# Install MariaDB
- name: Install MariaDB packages
  become: yes
  become_user: root
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - libmariadbd-dev
      - libmariadbclient-dev
  tags: mariadb

# enable mysql
- name: enable mysql
  become: yes
  become_user: root
  service:
    name: mysql
    state: restarted
    enabled: yes

# install python libraries for MySQL in python 3.
- name: install python libraries for MySQL
  become: yes
  become_user: root
  pip:
    executable: pip3
    name:
      - mysqlclient
      - PyMySQL
  tags: mariadb

# set to listen on defined bind-address.
- name: Set bind-address to {{ server_mariadb_bind_address }} for MariaDB
  become: yes
  become_user: root
  lineinfile:
    path: '/etc/mysql/mariadb.conf.d/50-server.cnf'
    line: "bind-address = {{ server_mariadb_bind_address }}"
  notify: restart mysql
  tags: mariadb

# restart mysql
- name: restart mysql
  become: yes
  become_user: root
  service:
    name: mysql
    state: restarted

# ==> secure database - equivalent to `mysql_secure_installation` script

- name: run mysql_secure_installation ansible module
  mysql_secure_installation:
    login_password: ''
    new_password: "{{ server_mariadb_root_password }}"
    user: root
    login_host: localhost
    hosts: [ 'localhost', '127.0.0.1', '::1' ]
    change_root_password: true
    remove_anonymous_user: true
    disallow_root_login_remotely: true
    remove_test_db: true
  register: mysql_secure
  notify: restart mysql

  # To see detailed output
- debug:
    var: mysql_secure

# add MySQL configuration file to root user home with password.
- name: add MySQL configuration file to root user with password.
  become: yes
  become_user: root
  template:
    src: dot-my.cnf.j2
    dest: /root/.my.cnf
  notify: restart mysql

# Flush privileges.
- name: MySQL - flush privileges
  become: yes
  become_user: root
  shell: mysql -u root --execute="FLUSH PRIVILEGES;"
#  when: root_pwd_check.rc == 0
  notify: restart mysql
  tags: mysql

# open firewall for MySQL
- name: Allow mysql/mariadb ports
  become: yes
  become_user: root
  ufw:
    rule: allow
    port: mysql
  notify: restart mysql
  tags: mariadb

# create non-root admin user?

# check if non-root admin user created.
- name: check if admin user {{ server_mariadb_admin_user }} exists
  shell: mysql -u root -p{{ server_mariadb_root_password }} -e 'SELECT DISTINCT User FROM mysql.user;' | grep {{ server_mariadb_admin_user }}
  register: admin_exists_check
  failed_when: admin_exists_check.rc == 2
  when: ( server_mariadb_admin_user != "" ) and ( server_mariadb_admin_user != "" )

# Creates database user {{ server_mariadb_admin_user }} and password {{ server_mariadb_admin_password }} with all database privileges and 'WITH GRANT OPTION'
- name: Create non-root admin user {{ server_mariadb_admin_user }}
  mysql_user:
    login_user: root
    login_password: "{{ server_mariadb_root_password }}"
    name: "{{ server_mariadb_admin_user }}"
    password: "{{ server_mariadb_admin_password }}"
    host: "{{ item }}"
    priv: '*.*:ALL,GRANT'
    state: present
  with_items:
    - "%"
    - ::1
    - 127.0.0.1
    - localhost
  when:
    - server_mariadb_admin_user != ""
    - server_mariadb_admin_password != ""
    - admin_exists_check.rc == 0
    - admin_exists_check.stdout == ""
  notify: restart mysql
  tags: mariadb