---

# clone the required git repos

# prerequisite: python_utilities
# - https://github.com/jonathanmorgan/python_utilities.git
# - git@github.com:jonathanmorgan/python_utilities.git
- name: clone python_utilities
  git:
    repo: https://github.com/jonathanmorgan/python_utilities.git
    dest: "{{ django_project_folder_path }}/python_utilities"

# prerequisite: django_config
# - https://github.com/jonathanmorgan/django_config.git
# - git@github.com:jonathanmorgan/django_config.git
- name: clone django_config
  git:
    repo: https://github.com/jonathanmorgan/django_config.git
    dest: "{{ django_project_folder_path }}/django_config"

# prerequisite: django_messages
# - https://github.com/jonathanmorgan/django_messages.git
# - git@github.com:jonathanmorgan/django_messages.git
- name: clone django_messages
  git:
    repo: https://github.com/jonathanmorgan/django_messages.git
    dest: "{{ django_project_folder_path }}/django_messages"

# sourcenet
# - https://github.com/jonathanmorgan/sourcenet.git
# - git@github.com:jonathanmorgan/sourcenet.git
- name: clone sourcenet
  git:
    repo: https://github.com/jonathanmorgan/sourcenet.git
    dest: "{{ django_project_folder_path }}/sourcenet"

# sourcenet_analysis
# - https://github.com/jonathanmorgan/sourcenet_analysis.git
# - git@github.com:jonathanmorgan/sourcenet_analysis.git
- name: clone sourcenet_analysis
  git:
    repo: https://github.com/jonathanmorgan/sourcenet_analysis.git
    dest: "{{ django_project_folder_path }}/sourcenet_analysis"

# create work folder "{{ django_project_folder_path }}/msu_phd_work"
- name: make sure there is a "{{ django_project_folder_path }}/msu_phd_work" folder
  file:
    path: "{{ django_project_folder_path }}/work"
    state: directory

# msu_phd_work
# - https://github.com/jonathanmorgan/msu_phd_work.git
# - git@github.com:jonathanmorgan/msu_phd_work.git
- name: clone msu_phd_work
  git:
    repo: https://github.com/jonathanmorgan/msu_phd_work.git
    dest: "{{ django_project_folder_path }}/work/msu_phd_work"

# install requirements

# update settings.py --> INSTALLED_APPS

# touch mod.wsgi to reload everything.