---

# clone the required git repos

# ==> prerequisite: python_utilities
# - https://github.com/jonathanmorgan/python_utilities.git
# - git@github.com:jonathanmorgan/python_utilities.git
- name: clone python_utilities
  git:
    repo: https://github.com/jonathanmorgan/python_utilities.git
    dest: "{{ django_project_folder_path }}/python_utilities"

# ==> prerequisite: django_config
# - https://github.com/jonathanmorgan/django_config.git
# - git@github.com:jonathanmorgan/django_config.git
- name: clone django_config
  git:
    repo: https://github.com/jonathanmorgan/django_config.git
    dest: "{{ django_project_folder_path }}/django_config"

# add to INSTALLED_APPS 
- name: add django_config to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'django_config.apps.Django_ConfigConfig' )
  notify: touch wsgi.py

# ==> prerequisite: django_messages
# - https://github.com/jonathanmorgan/django_messages.git
# - git@github.com:jonathanmorgan/django_messages.git
- name: clone django_messages
  git:
    repo: https://github.com/jonathanmorgan/django_messages.git
    dest: "{{ django_project_folder_path }}/django_messages"

# add to INSTALLED_APPS 
- name: add django_messages to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'django_messages.apps.DjangoMessagesConfig' )
  notify: touch wsgi.py

# ==> sourcenet
# - https://github.com/jonathanmorgan/sourcenet.git
# - git@github.com:jonathanmorgan/sourcenet.git
- name: clone sourcenet
  git:
    repo: https://github.com/jonathanmorgan/sourcenet.git
    dest: "{{ django_project_folder_path }}/sourcenet"

# add to INSTALLED_APPS 
- name: add sourcenet to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'sourcenet.apps.SourcenetConfig' )
  notify: touch wsgi.py

# add to urls.py 
- name: add sourcenet to urls.py
  lineinfile:
    path: '{{ django_config_folder_path }}/urls.py'
    line: urlpatterns.append( path( 'sourcenet/', include( 'sourcenet.urls' ) ) )
  notify: touch wsgi.py

# ==> sourcenet_analysis
# - https://github.com/jonathanmorgan/sourcenet_analysis.git
# - git@github.com:jonathanmorgan/sourcenet_analysis.git
- name: clone sourcenet_analysis
  git:
    repo: https://github.com/jonathanmorgan/sourcenet_analysis.git
    dest: "{{ django_project_folder_path }}/sourcenet_analysis"

# add to INSTALLED_APPS 
- name: add sourcenet_analysis to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'sourcenet_analysis.apps.Sourcenet_AnalysisConfig' )
  notify: touch wsgi.py

# add to urls.py 
- name: add sourcenet_analysis to urls.py
  lineinfile:
    path: '{{ django_config_folder_path }}/urls.py'
    line: urlpatterns.append( path( 'sourcenet/analysis/', include( 'sourcenet_analysis.urls' ) ) )
  notify: touch wsgi.py

# ==> msu_phd_work
# create work folder "{{ django_project_folder_path }}/msu_phd_work"
- name: make sure there is a "{{ django_project_folder_path }}/msu_phd_work" folder
  file:
    path: "{{ django_project_folder_path }}/work"
    state: directory

# clone git repo.
# - https://github.com/jonathanmorgan/msu_phd_work.git
# - git@github.com:jonathanmorgan/msu_phd_work.git
- name: clone msu_phd_work
  git:
    repo: https://github.com/jonathanmorgan/msu_phd_work.git
    dest: "{{ django_project_folder_path }}/work/msu_phd_work"

# install requirements

# update the database

# touch mod.wsgi to reload everything.