---

# clone the required git repos

# ==> prerequisite: python_utilities
# - https://github.com/jonathanmorgan/python_utilities.git
# - git@github.com:jonathanmorgan/python_utilities.git
- name: clone python_utilities
  git:
    repo: https://github.com/jonathanmorgan/python_utilities.git
    dest: "{{ django_project_folder_path }}/python_utilities"

# install python_utilities requirements
- name: install python_utilities requirements
  pip:
    requirements: "{{ django_project_folder_path }}/python_utilities/requirements.txt"
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# install python_utilities potgresql-specific requirements
- name: install python_utilities potgresql-specific requirements
  pip:
    requirements: "{{ django_project_folder_path }}/python_utilities/requirements_pgsql.txt"
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# ==> prerequisite: django_config
# - https://github.com/jonathanmorgan/django_config.git
# - git@github.com:jonathanmorgan/django_config.git
- name: clone django_config
  git:
    repo: https://github.com/jonathanmorgan/django_config.git
    dest: "{{ django_project_folder_path }}/django_config"

# add to INSTALLED_APPS 
- name: add django_config to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'django_config.apps.Django_ConfigConfig' )
  notify: touch wsgi.py

# install django_config requirements
- name: install django_config requirements
  pip:
    requirements: "{{ django_project_folder_path }}/django_config/requirements.txt"
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# ==> prerequisite: django_messages
# - https://github.com/jonathanmorgan/django_messages.git
# - git@github.com:jonathanmorgan/django_messages.git
- name: clone django_messages
  git:
    repo: https://github.com/jonathanmorgan/django_messages.git
    dest: "{{ django_project_folder_path }}/django_messages"

# add to INSTALLED_APPS 
- name: add django_messages to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'django_messages.apps.DjangoMessagesConfig' )
  notify: touch wsgi.py

# install django_messages requirements
- name: install django_messages requirements
  pip:
    requirements: "{{ django_project_folder_path }}/django_messages/requirements.txt"
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# ==> sourcenet
# - https://github.com/jonathanmorgan/sourcenet.git
# - git@github.com:jonathanmorgan/sourcenet.git
- name: clone sourcenet
  git:
    repo: https://github.com/jonathanmorgan/sourcenet.git
    dest: "{{ django_project_folder_path }}/sourcenet"

# add to INSTALLED_APPS 
- name: add sourcenet to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'sourcenet.apps.SourcenetConfig' )
  notify: touch wsgi.py

# add to urls.py 
- name: add sourcenet to urls.py
  lineinfile:
    path: '{{ django_config_folder_path }}/urls.py'
    line: urlpatterns.append( path( 'sourcenet/', include( 'sourcenet.urls' ) ) )
  notify: touch wsgi.py

# install sourcenet requirements
- name: install sourcenet requirements
  pip:
    requirements: "{{ django_project_folder_path }}/sourcenet/requirements.txt"
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# ==> sourcenet_analysis
# - https://github.com/jonathanmorgan/sourcenet_analysis.git
# - git@github.com:jonathanmorgan/sourcenet_analysis.git
- name: clone sourcenet_analysis
  git:
    repo: https://github.com/jonathanmorgan/sourcenet_analysis.git
    dest: "{{ django_project_folder_path }}/sourcenet_analysis"

# add to INSTALLED_APPS 
- name: add sourcenet_analysis to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'sourcenet_analysis.apps.Sourcenet_AnalysisConfig' )
  notify: touch wsgi.py

# add to urls.py 
- name: add sourcenet_analysis to urls.py
  lineinfile:
    path: '{{ django_config_folder_path }}/urls.py'
    line: urlpatterns.append( path( 'sourcenet/analysis/', include( 'sourcenet_analysis.urls' ) ) )
  notify: touch wsgi.py

# install sourcenet_analysis requirements
- name: install sourcenet_analysis requirements
  pip:
    requirements: "{{ django_project_folder_path }}/sourcenet_analysis/requirements.txt"
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# ==> sourcenet_datasets
# - https://github.com/jonathanmorgan/sourcenet_datasets.git
# - git@github.com:jonathanmorgan/sourcenet_datasets.git
- name: clone sourcenet_datasets
  git:
    repo: https://github.com/jonathanmorgan/sourcenet_datasets.git
    dest: "{{ django_project_folder_path }}/sourcenet_datasets"

# add to INSTALLED_APPS 
- name: add sourcenet_datasets to INSTALLED_APPS in settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: INSTALLED_APPS.append( 'sourcenet_datasets.apps.SourcenetDatasetsConfig' )
  notify: touch wsgi.py

# add to urls.py 
- name: add sourcenet_datasets to urls.py
  lineinfile:
    path: '{{ django_config_folder_path }}/urls.py'
    line: urlpatterns.append( path( 'sourcenet/datasets/', include( 'sourcenet_datasets.urls' ) ) )
  notify: touch wsgi.py

# install sourcenet_datasets requirements
- name: install sourcenet_datasets requirements
  pip:
    requirements: "{{ django_project_folder_path }}/sourcenet_datasets/requirements.txt"
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# ==> msu_phd_work
# create work folder "{{ django_project_folder_path }}/work"
- name: make sure there is a "{{ django_project_folder_path }}/work" folder
  file:
    path: "{{ django_project_folder_path }}/work"
    state: directory

# clone git repo.
# - https://github.com/jonathanmorgan/msu_phd_work.git
# - git@github.com:jonathanmorgan/msu_phd_work.git
- name: clone msu_phd_work
  git:
    repo: https://github.com/jonathanmorgan/msu_phd_work.git
    dest: "{{ django_project_folder_path }}/work/msu_phd_work"

# ==> update the database
- name: run `python manage.py migrate`
  django_manage:
    app_path: "{{ django_project_folder_path }}"
    command: migrate
    virtualenv: "{{ django_virtualenv_path }}"
  notify: touch wsgi.py

# collect static
- name: run `python manage.py collectstatic`
  django_manage:
    app_path: "{{ django_project_folder_path }}"
    command: collectstatic --noinput
    virtualenv: "{{ django_virtualenv_path }}"

# ==> update settings to include login variables

# add leading comment
- name: add sourcenet leading comment to settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: '# login configuration'
  notify: touch wsgi.py

# add LOGIN_URL
- name: add LOGIN_URL to settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: "LOGIN_URL = '/{{ django_project_name }}/sourcenet/accounts/login/'"
  notify: touch wsgi.py

# add LOGIN_REDIRECT_URL
- name: add LOGIN_REDIRECT_URL to settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: "LOGIN_REDIRECT_URL = '/{{ django_project_name }}/sourcenet/output/network/'"
  notify: touch wsgi.py

# add LOGOUT_URL
- name: add LOGOUT_URL to settings.py
  lineinfile:
    path: '{{ django_config_folder_path }}/settings.py'
    line: "LOGOUT_URL = '/'"
  notify: touch wsgi.py

# should end up touch-ing wsgi.py to reload everything.

# new index.html
- name: add index.html to webroot
  become: yes
  become_user: root
  template:
    src: index.html.j2
    dest: '/var/www/html/index.html'

# also add python_resources.html
- name: add python_resources.html to webroot
  become: yes
  become_user: root
  template:
    src: python_resources.html.j2
    dest: '/var/www/html/python_resources.html'
