# jupyterhub installation defaults
jupyterhub_name: jupyterhub

# jupyterhub installation
jupyterhub_install_folder_path: /opt/{{ jupyterhub_name }}
jupyterhub_venv_folder_path: "{{ jupyterhub_install_folder_path }}/venv"
jupyterhub_venv_bin_folder_path: "{{ jupyterhub_venv_folder_path }}/bin"
jupyterhub_venv_activate_path: "{{ jupyterhub_venv_bin_folder_path }}/activate"
jupyterhub_bin_folder_path: "{{ jupyterhub_venv_bin_folder_path }}"
jupyterhub_bin_path: "{{ jupyterhub_bin_folder_path }}/{{ jupyterhub_name }}"

# jupyterhub configuration
jupyterhub_config_folder_path: /etc/{{ jupyterhub_name }}
jupyterhub_config_folder: "{{ jupyterhub_config_folder_path }}"
jupyterhub_config_file_name: jupyterhub_config.py
jupyterhub_config_file_path: "{{ jupyterhub_config_folder_path }}/{{ jupyterhub_config_file_name }}"

# jupyterhub environment file
jupyterhub_env_file_name: jupyterhub_environment
jupyterhub_env_file_path: "{{ jupyterhub_config_folder }}/{{ jupyterhub_env_file_name }}"

# more jupyterhub configuration
jupyterhub_configproxy_auth_token: pleasegenerateanewauthtokendontjustusethisdefault
jupyterhub_proxy_command_path: ""
jupyterhub_admin_user_list: "'{{ ansible_user }}'"
jupyterhub_whitelist_list: "'{{ ansible_user }}'"
jupyterhub_ssl_certificate_path: "{{ server_ssl_certificate_path }}"
jupyterhub_ssl_private_key_path: "{{ server_ssl_private_key_path }}"
jupyterhub_proxy_command_path: "/usr/local/bin/configurable-http-proxy"

# start single-user servers
jupyterhub_spawner_cmd: jupyterhub-singleuser

# systemd service
jupyterhub_systemd_service_path: "/etc/systemd/system/jupyterhub.service"
