# default variables for host research.local
python_3_path: /usr/bin/python3
python_base_version: "3.10"
ansible_user: research
ansible_python_interpreter: "{{ python_3_path }}"
# ansible_become: yes
ansible_become_user: root
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;dev
          39323463633961373564303438366439333734656662383337623833663837393932303138393838
          3839333563303364323362393063656466306237393132340a343364653962613935626134646462
          36333031633639633034616531666465343434653536636532393933613634616234376635343538
          3935353466623761380a306564643635343432343166326236663761393931396431616637306535
          3863

# configuration
server_host_name: research
server_name: "{{ server_host_name }}.local"
server_ip_address: 172.16.111.134
#server_ubuntu_version: "18.04"
#server_ubuntu_version_code_name: bionic
#server_ubuntu_version: "20.04"
#server_ubuntu_version_code_name: focal
server_ubuntu_version: "22.04"
server_ubuntu_version_code_name: jammy
server_cpu_type: amd64
#server_cpu_type: arm64 # M1 mac VM guest
ansible_user_home_folder: /home/{{ ansible_user }}
work_folder: "{{ ansible_user_home_folder }}/work"
log_folder: "{{ ansible_user_home_folder }}/logs"
server_webroot_folder: /var/www/html
server_ssl_certificate_path: ""
server_ssl_private_key_path: ""

# apache configuration
apache_server_ssl_site_config: default-ssl

# virtualenvwrapper configuration
virtualenv_parent_folder: "{{ ansible_user_home_folder }}"
virtualenv_folder: "{{ virtualenv_parent_folder }}/.virtualenvs"
virtualenv_project_folder: "{{ work_folder }}/vew-projects"

# postgresql configuration
# ubuntu 16.04
#server_pgsql_version: "9.5"
# ubuntu 18.04
#server_pgsql_version: "10"
# ubuntu 20.04
#server_pgsql_version: "12"
# ubuntu 22.04
server_pgsql_version: "14"
server_pgsql_listen_addresses: "localhost,127.0.0.1,{{ server_ip_address }},{{ server_name }}"
server_pgsql_admin_user: "{{ ansible_user }}"
server_pgsql_admin_password: "{{ ansible_become_password }}"
server_pgsql_python_package: psycopg2

# MariaDB configuration
server_mariadb_bind_address: "::"
server_mariadb_root_password: "{{ ansible_become_password }}"
server_mariadb_admin_user: "{{ ansible_user }}"
server_mariadb_admin_password: "{{ ansible_become_password }}"

# MySQL configuration
# server type can be "mariadb" or ""
server_mysql_type: "mariadb"
server_mysql_bind_address: "::"
server_mysql_root_password: "{{ ansible_become_password }}"
server_mysql_admin_user: "{{ ansible_user }}"
server_mysql_admin_password: "{{ ansible_become_password }}"

# R configuration
#r_apt_deb_ubuntu_version_path: "{{ server_ubuntu_version_code_name }}-cran{{ r_version_number }}"
r_apt_deb_ubuntu_version_path: "{{ server_ubuntu_version_code_name }}"
# R 4.0+:
r_version_number: "40"
r_marutter_version_number: "4.0"
# R 3.5:
#r_version_number: "35"
#r_marutter_version_number: "3.5"

# RStudio server configuration
#rstudio_ubuntu_codename: {{ server_ubuntu_version_code_name }}
#rstudio_version: 2022.02.3-492

# Jupyterhub configuration
#jupyterhub_config_folder: /etc/jupyterhub
jupyterhub_configproxy_auth_token: 8da752f8de9494b495aaa619bb5c2c8a7a163a0643b91fb57ec0ff9e0392ec85
jupyterhub_proxy_command_path: ""
jupyterhub_admin_user_list: "'{{ ansible_user }}'"
jupyterhub_whitelist_list: "'{{ ansible_user }}'"
jupyterhub_ssl_certificate_path: "{{ server_ssl_certificate_path }}"
jupyterhub_ssl_private_key_path: "{{ server_ssl_private_key_path }}"

#jupyterhub_proxy_command_path: "/usr/local/bin/configurable-http-proxy"

#=========================================================#
# django project configuration - defaults in:
#     - roles/django_project/defaults/main.yml
#=========================================================#

# django project basics
django_project_name: research
django_project_base_folder_path: "{{ work_folder }}/django/{{ django_project_name }}"
#django_project_base_folder_path: "/opt/django/{{ django_project_name }}"
#django_project_folder_path: "{{ django_project_base_folder_path }}/{{ django_project_name }}"

# django project virtualenv
#django_virtualenv_home_path: "{{ virtualenv_folder }}"
#django_virtualenv_name: "{{ django_project_name }}"
#django_virtualenv_python: "{{ python_3_path }}"
#django_virtualenv_path: "{{ django_virtualenv_home_path }}/{{ django_virtualenv_name }}"
#django_virtualenv_bin_path: "{{ django_virtualenv_path }}/bin"
#django_virtualenv_python_version: "{{ python_base_version }}"  # major.minor, no worry about part after that (so for 3.7.7, just use 3.7)

# for older versions of django, it is "django-admin.py". For newer (post-3.2?) it is just "django-admin".
#django_admin_command: "django-admin.py"
#django_admin_command: "django-admin"

# django project locations configuration
#django_config_folder_path: "{{ django_project_folder_path }}/{{ django_project_name }}"
#django_logs_folder_path: "{{ django_project_base_folder_path }}/logs"
#django_log_file_path: "{{ django_logs_folder_path }}/django-{{ django_project_name }}.log"
#django_static_folder_path: "{{ server_webroot_folder }}/static"
#django_settings_import: "{{ django_project_name }}.settings"

# database configuration
#db_postgresql_python_package: "psycopg2-binary"
#django_db_python_package: "{{ db_postgresql_python_package }}"
#django_db_package: "{{ server_pgsql_python_package }}"
#django_db_name: "{{ django_project_name }}"
#django_db_username: "django_user"
#django_db_password: "{{ ansible_become_password }}"
#django_db_host: "localhost"
#db_postgresql_port: "5432"
#django_db_port: "{{ db_postgresql_port }}"  # 5432 for postgresql, 3306 for mysql.

# create database things?
#django_db_create_db_user: false
#django_db_create_database: false

# django security setup
# generate random secret key: openssl rand -base64 64
#django_secret_key: "changemeplease"

# django superuser setup
#django_superuser_username: "{{ ansible_user }}"
#django_superuser_password: "{{ ansible_become_password }}"
#django_superuser_email: ""

# phd work
#include_phd_work: false
