# postgresql configuration
# ubuntu 16.04
#server_pgsql_version: "9.5"
# ubuntu 18.04
#server_pgsql_version: "10"
# ubuntu 20.04
#server_pgsql_version: "12"
# ubuntu 22.04
server_pgsql_version: "14"
server_pgsql_listen_addresses: "localhost,127.0.0.1,{{ server_ip_address }},{{ server_name }}"
server_pgsql_admin_user: "{{ ansible_user }}"
server_pgsql_admin_password: "{{ ansible_become_password }}"
server_pgsql_python_package: psycopg2
